name: Licenses and permissions
uses: lowlighter/metrics@latest
with:
  filename: assets/metrics.plugin.licenses.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  template: repository
  repo: VMAware
  plugin_licenses: yes
  plugin_licenses_legal: yes